[package]
name = "fluorite_codegen"
documentation = "https://docs.rs/fluorite"
readme = "../README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
exclude.workspace = true

[lib]
name = "fluorite_codegen"
path = "src/lib.rs"

[[bin]]
name = "fluorite"
path="src/main.rs"

[dependencies]
anyhow = "1.0"
askama = "0.12"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["serde_derive"] }
fluorite = { path = "../runtime/", version = "0.6.0" }
derive-new = "0.7"
logos = "0.14"
chumsky = "0.9"
ariadne = "0.4"
